---
name: 'Setup Wren CLI'
author: Yevhen Fabizhevskyi
description: 'This action sets up a wren CLI to run wren scripts.'
branding:
  icon: terminal
  color: gray-dark
inputs:
  version:
    description: 'Wren CLI version.'
    required: false
    default: 0.3.0
runs:
  using: 'node16'
  main: 'dist/index.js'
