---
name: 'Setup Wren CLI'
author: Yevhen Fabizhevskyi
description: 'This action sets up a wren CLI to run wren scripts.'
branding:
  icon: terminal
  color: gray-dark
inputs:
  version:
    description: 'Wren CLI version.'
    required: false
    default: 0.4.0
runs:
  using: 'composite'
  steps:
    - name: Collect info
      id: info
      run: |
        if [[ "${{ runner.os }}" == "Windows" ]]; then
          WREN_EXEC_NAME=wren_cli.exe
          WREN_BINARY_NAME=windows
        else
          WREN_EXEC_NAME=wren_cli
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            WREN_BINARY_NAME=linux
          else
            WREN_BINARY_NAME=mac
          fi
        fi
        echo "WREN_EXEC_NAME=$WREN_EXEC_NAME" >> $GITHUB_OUTPUT
        echo "WREN_BINARY_NAME=$WREN_BINARY_NAME" >> $GITHUB_OUTPUT
        WREN_INSTALLED=$(if command -v $WREN_EXEC_NAME >/dev/null 2>&1; then echo true; else echo false; fi)
        echo "WREN_INSTALLED=$WREN_INSTALLED" >> $GITHUB_OUTPUT
        mkdir -p "$RUNNER_TEMP/wren"
        echo "WREN_PATH=$RUNNER_TEMP/wren" >> $GITHUB_OUTPUT
      shell: bash
    - name: Install wren (Linux, macOS)
      if: ${{ steps.info.outputs.WREN_INSTALLED == 'false' && runner.os != 'Windows'}}
      env:
        DOWNLOAD_URL: https://github.com/wren-lang/wren-cli/releases/download/${{ inputs.version }}/wren_cli-${{ steps.info.outputs.WREN_BINARY_NAME }}-${{ inputs.version }}.zip
      run: |
        wget -q -O wren.zip $DOWNLOAD_URL && unzip wren.zip && rm -f wren.zip
        exe_path=$(find . -name "${{ steps.info.outputs.WREN_EXEC_NAME }}")
        bin_path=$(dirname $exe_path)
        echo "$bin_path" >> $GITHUB_PATH
      shell: bash
      working-directory: ${{ steps.info.outputs.WREN_PATH }}
