---
name: "Setup Wren CLI"
author: Yevhen Fabizhevskyi
description: "This action sets up a wren CLI to run wren scripts."
branding:
  icon: terminal
  color: gray-dark
inputs:
  version:
    description: wren CLI version. Defaults to the latest version.
    required: false
    default: "latest"
  force:
    description: |
      If "false" skips installation if wren CLI is already installed. If "true"
      installs wren CLI in any case. Defaults to "false".
    required: false
    default: "false"
  github-token:
    description: |
      GitHub token that is used to send requests to GitHub API such as getting
      latest release. Defaults to the token provided by GitHub Actions environment.
    required: false
    default: ${{ github.token }}
outputs:
  installed:
    description: Whether wren CLI was installed or not.
    value: "${{ steps.install-wren-cli.outcome == 'success' }}"
runs:
  using: "composite"
  steps:
    - name: Collect info
      id: info
      env:
        INPUT_FORCE: "${{ inputs.force }}"
      run: ./collect-info.sh "${INPUT_FORCE}"
      shell: sh
      working-directory: "${{ github.action_path }}/src"

    - name: Download binary
      if: ${{ steps.info.outputs.bin-installed == 'false' }}
      id: download-binary
      uses: robinraju/release-downloader@v1
      with:
        repository: "wren-lang/wren-cli"
        latest: "${{ inputs.version == 'latest' }}"
        tag: "${{ inputs.version != 'latest' && inputs.version || '' }}"
        fileName: "wren*cli-${{ runner.os == 'Linux' && 'linux' || (runner.os == 'macOS' && 'mac' || 'windows') }}-*.zip"
        extract: "true"
        out-file-path: "${{ steps.info.outputs.bin-dir }}"
        token: "${{ inputs.github-token }}"

    - name: Install wren CLI
      if: ${{ steps.info.outputs.bin-installed == 'false' }}
      id: install-wren-cli
      run: |
        tag_name="${{ steps.download-binary.outputs.tag_name }}"
        sep="${{ steps.download-binary.outputs.tag_name == '0.3.0' && '_' || '-' }}"
        subdir="/wren${sep}cli-${{ runner.os == 'Linux' && 'linux' || (runner.os == 'macOS' && 'mac' || 'windows') }}-${tag_name}"
        if [ "${tag_name}" = "0.3.0" ] && [ "${RUNNER_OS}" != "Linux" ]; then
          subdir=""
        fi
        bin_path="${{ steps.info.outputs.bin-path }}${subdir}"
        if [ "${RUNNER_OS}" != "Windows" ]; then
          chmod +x "${bin_path}/wren_cli"
        fi
        ls -la "${bin_path}"
        echo "${bin_path}" >> "$GITHUB_PATH"
      shell: sh

    - name: Print version
      run: wren_cli --version
      shell: sh
