---
name: Merge PR

on:
  check_suite:
    types: [completed]

jobs:
  print_hello:
    name: Print Hello
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'pre-commit-ci-update-config' }}
    steps:
      - name: Print
        run: echo 'Hello ${{ toJSON(job) }}!'
        shell: bash
      - name: Test
        uses: actions/github-script@v6
        with:
          script: |
            console.log(context);
#            const path = require('path');
#            const workflowFileName = path.basename(module.filename);
#
#            const { check_suite_id } = octokit.rest.actions.listWorkflowRuns({
#              owner: context.repo.owner,
#              repo: context.repo.repo,
#              workflowFileName,
#            });
#            const res = github.rest.checks.getSuite({
#              owner: context.repo.owner,
#              repo: context.repo.repo,
#              check_suite_id,
#            });
#            console.log(res);
