---
name: Merge PR

on:
  check_suite:
    types: [completed]

jobs:
  print_hello:
    name: Print Hello
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'pre-commit-ci-update-config' }}
    steps:
      - name: Print
        run: echo 'Hello ${{ toJSON(job) }}!'
        shell: bash
      - name: Test
        uses: actions/github-script@v6
        with:
          script: |
            console.log(context);
#            console.log('-------!--------');
#            const { data } = await github.rest.checks.listForRef({
#              owner: context.repo.owner,
#              repo: context.repo.repo,
#              ref: context.ref,
#            });
#            console.log(data.check_runs[0]);
#            console.log(data.check_runs[1]);
