---
name: Merge PR

on:
  check_suite:
    types: [completed]

jobs:
  print_hello:
    name: Print Hello
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'pre-commit-ci-update-config' }}
    steps:
      - name: Print
        run: echo 'Hello ${{ toJSON(payload) }}!'
        shell: bash
