---
name: Merge PR

on:
  check_run:
    types: [completed]

jobs:
  print_hello:
    name: Print Hello!
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: echo 'Hello ${{ github.ref_name }}!'
        shell: bash
